### ⚠️ 变量配置区
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTgxY2NjNjA5YjY1MGZlNjgzNTg3MzgiLCJyb2xlIjoibWVyY2hhbnQiLCJ1c2VybmFtZSI6Im1lcmNoYW50XzAxIiwiaWF0IjoxNzcwMTE0MjU2LCJleHAiOjE3NzAyMDA2NTZ9.0rJzzGOwjp52RvNMYaEg_rlmQ72XDXK_oafSLkAtRsk
@hotel_id = 6981d099143746681dcf0175

### 1. 添加房型 (价格 5000，低于酒店原价 9999)
POST http://localhost:5000/api/rooms
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "hotelId": "{{hotel_id}}",
  "title": "云端大床房",
  "price": 5000,
  "capacity": 2,
  "bedInfo": "1张2米特大床",
  "size": "60m²"
}

### 2. 再次添加一个更便宜的房型 (价格 3000)
POST http://localhost:5000/api/rooms
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "hotelId": "{{hotel_id}}",
  "title": "特惠双床房",
  "price": 3000,
  "capacity": 2,
  "bedInfo": "2张1.2米床",
  "size": "50m²"
}

### 3. 查看该酒店的所有房型
GET http://localhost:5000/api/rooms/{{hotel_id}}

### 4. (验证) 再次去查酒店信息，看看 minPrice 是否自动变成了 3000
GET http://localhost:5000/api/hotels/{{hotel_id}}