### 测试图片上传
POST http://localhost:5000/api/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

< ./image/test_image.jpg
--WebAppBoundary--